const SEND_TOKEN_ADDRESS = "SENDdRQtYMWaQrBroBrJ2Q53fgVuq95CV9UPGEvpCxa"
const PYUSD_TOKEN_ADDRESS = "2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo"
const SKID_TOKEN_ADDRESS = "9X2RHtKrBzw3SLYe9E88cBd1kz5RfU1f4JTSn4aRH43d"
const IMAGE_DEFAULT = "https://i.imgur.com/CXh9lkt.jpeg"

module.exports = {
  SEND_TOKEN_ADDRESS,
  PYUSD_TOKEN_ADDRESS,
  SKID_TOKEN_ADDRESS,
  IMAGE_DEFAULT
}
